version: "2.2"

services:

  apiservice:
    build: ./services
    expose:
      - 5000
    volumes:
      - ./services/db.sqlite3:/usr/local/services/db.sqlite3
    restart: unless-stopped


  annotation_screen:
    build: ./AnnotationScreen
    ports:
      - 80:80
    depends_on:
      - apiservice
    volumes:
      - ./AnnotationScreen/src/assets/:/usr/share/nginx/html/assets/
    working_dir: /usr/local/annotation_screen/