# Generated by Django 3.1.2 on 2022-03-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ImageId', models.IntegerField()),
                ('AnnotationText', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ImageName', models.CharField(max_length=100)),
            ],
        ),
    ]
