# Generated by Django 3.1.2 on 2022-04-11 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='Color',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
