# Generated by Django 3.1.2 on 2022-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0002_annotations_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='ParentObject',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
