# Generated by Django 3.2.4 on 2022-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0003_annotations_parentobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotations',
            old_name='AnnotationText',
            new_name='ObjectName',
        ),
        migrations.AddField(
            model_name='annotations',
            name='Shape',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
