# Generated by Django 3.1.2 on 2022-05-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0005_annotations_workerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
