# Generated by Django 3.2.4 on 2022-06-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0006_images_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='Part',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
