# Generated by Django 3.2.4 on 2022-06-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0008_auto_20220611_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='PartObject',
            field=models.CharField(blank=True, default='df', max_length=300),
            preserve_default=False,
        ),
    ]
