# Generated by Django 3.2.4 on 2022-06-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0009_alter_annotations_partobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='PartObject',
            field=models.CharField(max_length=300),
        ),
    ]
