# Generated by Django 3.2.4 on 2022-06-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0011_alter_annotations_partobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Label',
            new_name='Pred1Label',
        ),
        migrations.AddField(
            model_name='images',
            name='Pred1Score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='Pred2Label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='Pred2Score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='Pred3Label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='Pred3Score',
            field=models.IntegerField(null=True),
        ),
    ]
