# Generated by Django 3.2.4 on 2022-06-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0012_auto_20220612_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('WorkerId', models.CharField(max_length=300)),
                ('Consent', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='annotations',
            name='Shape',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='WorkerId',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
