# Generated by Django 3.2.4 on 2022-06-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0014_images_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='ImageName',
            new_name='Filename',
        ),
    ]
