# Generated by Django 3.2.4 on 2022-06-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0015_rename_imagename_images_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Filename',
            new_name='ImageName',
        ),
    ]
