# Generated by Django 3.2.13 on 2022-06-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0017_images_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Iteration',
            field=models.IntegerField(default=0),
        ),
    ]
