# Generated by Django 3.2.13 on 2022-06-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0019_auto_20220620_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='DateSubmitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
