# Generated by Django 3.2.13 on 2022-06-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0020_alter_annotations_datesubmitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='DateSubmitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
