# Generated by Django 3.2.13 on 2022-06-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0021_consent_datesubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='DateFetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
